baseURL = 'https://fiecarevoce.com/'
locale = 'ro-RO'
title = 'Fiecare Voce'
theme = 'blowfish'
defaultContentLanguage = 'ro'
enableRobotsTXT = true
summaryLength = 25
disableHugoGeneratorInject = true
paginate = 6
removePathAccents = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  authors = "authors"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[imaging]
  quality = 85
  hint = "photo"
  anchor = "smart"

[imaging.exif]
  disableDate = false
  disableLatLong = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

