baseURL = 'https://fiecarevoce.com/'
locale = 'ro-RO'
title = 'Fiecare Voce'
theme = 'blowfish'
defaultContentLanguage = 'ro'
enableRobotsTXT = true
summaryLength = 25
disableHugoGeneratorInject = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
