baseURL = 'https://fiecarevoce.com/'
locale = 'ro-RO'
title = 'Fiecare Voce'
theme = 'blowfish'
defaultContentLanguage = 'ro'
enableRobotsTXT = true
summaryLength = 25
disableHugoGeneratorInject = true
paginate = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
