[[main]]
  name = "Despre Noi"
  url = "/despre-noi/"
  weight = 10

[[main]]
  name = "Impact"
  url = "/#impact"
  weight = 30

[[main]]
  name = "Proiecte"
  url = "/#proiecte"
  weight = 35

[[main]]
  name = "Articole"
  url = "/posts/"
  weight = 40

[[main]]
  name = "Implică-te"
  url = "/#implica-te"
  weight = 50
