[[main]]
  name = "Articole"
  url = "/posts/"
  weight = 10

[[main]]
  name = "Autori"
  url = "/authors/"
  weight = 20

[[main]]
  name = "Realizări"
  url = "/categories/realizari/"
  weight = 30

[[main]]
  name = "Impact"
  url = "/#impact"
  weight = 40

[[main]]
  name = "Despre Noi"
  url = "/despre-noi/"
  weight = 50

