colorScheme = "custom"
defaultAppearance = "light"
autoSwitchAppearance = false
showAppearanceSwitcher = false
enableSearch = true
enableCodeCopy = true
robots = "index, follow"
description = "Fiecare Voce este o platforma pentru dezvoltare comunitară, educație civică și inițiative sociale."
keywords = ["ONG", "tineret", "voluntariat", "lideri comunitari", "advocacy", "sustenabilitate", "schimbare sociala"]
defaultSocialImage = "images/og-logo.webp"
images = ["images/og-logo.webp"]

[author]
  name = "Fiecare Voce"
  email = "fiecarevoce@gmail.com"
  [author.links]
    instagram = "https://www.instagram.com/fiecarevoce"

[header]
  layout = "flex"
  showTitle = false
  showLogo = true
  logo = "images/logo1000.webp"
  disableTextInHeader = true

[footer]
  showCopyright = true
  showThemeAttribution = false

[homepage]
  layout = "custom"
  showRecent = true
  showRecentItems = 3

[seo]
  metaDescriptionOrder = ["summary", "description", "site"]

[sitemap]
  excludedKinds = ["taxonomy", "term"]
